Fibonacci Numbers base exercise
VladFiliucov/go-tn pull request #1
Opened 2020-10-13 23:41 UTC by VladFiliucov

Наверно ошибку все-таки не стоит выбрасывать, если аргумент больше 20? Просто хотел подключить какой-нибудь пакет :)

Было бы круто разобрать как go mod работает по лучше, потому-что я часа полтора убил пытаясь понять почему мой редактор не мог импортнуть автоматический пакет по названию функции - а оказалось, что нужно было функцию с заглавной буквы писать.

2020-10-14 05:55 UTC, DmitriyVTitov commented
> Было бы круто разобрать как go mod работает по лучше, потому-что я часа полтора убил пытаясь понять почему мой редактор не мог импортнуть автоматический пакет по названию функции - а оказалось, что нужно было функцию с заглавной буквы писать.

Это не go.mod, а область видимости в Go. Я об этом говорил.
К тому же, первая лекция по самому языку, по синтаксису, ещё впереди :)

2020-10-14 06:01 UTC, DmitriyVTitov requested changes
Не сходится (https://en.wikipedia.org/wiki/Fibonacci_number)
=== RUN   TestFib
    fibo_test.go:7: Число №1: 1
    fibo_test.go:7: Число №2: 2
    fibo_test.go:7: Число №3: 3
    fibo_test.go:7: Число №4: 5
    fibo_test.go:7: Число №5: 8
    fibo_test.go:7: Число №6: 13
    fibo_test.go:7: Число №7: 21

2020-10-14 06:01 UTC, DmitriyVTitov commented on homework-1/pkg/fibb/fibb.go
> +		os.Exit(1)
я не жду от подключаемого пакета, что он аварийно завершит мою программу!
надо или вернуть ошибку, или ограничиться (пока) надписью о превышении значения.

2020-10-14 06:01 UTC, DmitriyVTitov commented on homework-1/pkg/fibb/fibb.go
> +func Fib(n int) int {
экспортируемая функция должна иметь комментарий

2020-10-15 22:43 UTC, VladFiliucov commented on homework-1/pkg/fibb/fibb.go
> +		os.Exit(1)
но число мне все равно нужно вернуть, даже если я ошибку верну.

2020-10-16 23:46 UTC, DmitriyVTitov approved these changes
Теперь алгоритм правильный, всё хорошо.

2020-10-16 23:46 UTC, DmitriyVTitov commented on homework-1/pkg/fibb/fibb.go
> +	}
как я и говорил на втором занятии, этому условию не место в библиотеке
этому место в пакете бизнес-логики (mian в данном случае)

2020-10-17 09:38 UTC, merged